import CategoryType from '../src/model/Category'
import QuestionType from "../src/model/QuestionType"
export const questionList: QuestionType[] = [
   {
      category: CategoryType.Transport,
      sentence: 'Un aller-retour Paris-Bordeaux en voiture',
      quantity: 50,
      hypothesis :'Berline 5cv essence - typeRenault Scenic',
      alternatives: 'le bus ou le train',
   },
   {
      category: CategoryType.Transport,
      sentence: 'Paris Marseille en avion',
      quantity: 200,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Transport,
      sentence: 'Lille-New-York en avion',
      quantity: 400,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Transport,
      sentence: 'Paris-marseille en train',
      quantity: 1,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Transport,
      sentence: '10 km en vélo',
      quantity: 0,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Transport,
      sentence: '10km en bus',
      quantity: 2,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Maison,
      sentence: 'un radiateur électrique pendant une demie-journée',
      quantity: 4,
      hypothesis :'radiateur standard (50w)',
      alternatives: '?',
   },
   {
      category: CategoryType.Maison,
      sentence: 'une ampoule (classique) allumée pendant une journée',
      quantity: 1,
      hypothesis :'Ampoule 100W',
      alternatives: 'Ampoule à LED',
   },
   {
      category: CategoryType.Maison,
      sentence: 'une ampoule (led) allumée pendant une journée',
      quantity: 0.1,
      hypothesis :'Ampoule Led (equivalent 100W)',
      alternatives: '?',
   },
   {
      category: CategoryType.Nourriture,
      sentence: '1 kilo d’oranges (origine France)',
      quantity: 2,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Nourriture ,
      sentence: '1 kilo d’oranges (origine Venezuela)',
      quantity: 20,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Nourriture,
      sentence: '1 steak (origine France)',
      quantity: 1,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Nourriture,
      sentence: '1 steak origine Argentine',
      quantity: 20,
      hypothesis :'',
      alternatives: '',
   },
   {
      category: CategoryType.Objet,
      sentence: 'Achat d’un 1 smartphone neuf',
      quantity: 20,
      hypothesis :'Iphone 8 plus neuf',
      alternatives: 'Un smartphone d’occasion !',
   },
   {
      category: CategoryType.Objet,
      sentence: 'Achat d’un téléviseur neuf',
      quantity: 40,
      hypothesis :'Samsung Gna gna ',
      alternatives: '',
   },
]